title = "Renato Vassallo"
baseURL = "https://renatovassallo.github.io/"
languageCode = "en-us"
theme = "ananke"
#resourceDir = "../resources"

MetaDataFormat = "toml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Renato Vassallo"
  favicon = ""
  description = ""
  facebook = ""
  linkedIn = "https://www.linkedin.com/in/renatovassallo"
  twitter = "https://twitter.com/VassalloSarango"
  github = "https://github.com/RenatoVassallo"
  #site_logo = "/images/cover/network.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
